; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200



lib_deps = 
	mikalhart/TinyGPSPlus
	mobizt/Firebase ESP32 Client@^3.9.8
	knolleary/PubSubClient@^2.8
	duinowitchery/hd44780
	bblanchon/ArduinoJson



[env:test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_flags = -D RUN_TESTS
lib_deps =
    mobizt/Firebase ESP32 Client@^3.9.8
    mikalhart/TinyGPSPlus
    knolleary/PubSubClient@^2.8
    duinowitchery/hd44780
    bblanchon/ArduinoJson